theme: jekyll-theme-tactile
github:
  public: true
  macos_url: https://github.com/mgree/ffs/releases/download/macos-latest/ffs
  linux_url: https://github.com/mgree/ffs/releases/download/ubuntu-latest/ffs
  
