theme: jekyll-theme-tactile
repository: mgree/ffs
github:
  public: true
  macos_url: https://github.com/mgree/ffs/releases/download/latest/ffs.macos
  linux_url: https://github.com/mgree/ffs/releases/download/latest/ffs.linux
exclude:
  - Gemfile
