name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install FUSE (Ubuntu)
        run: sudo apt-get install fuse libfuse-dev pkg-config
        if: ${{ matrix.os == "ubuntu-latest" }}

      - name: Install FUSE (macOS)
        run: sudo brew install macfuse pkg-config
        if: ${{ matrix.os == "macos-latest" }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test ffs
        run: |
          cargo build --verbose --all
          cargo test
        
