name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install FUSE
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get install fuse libfuse-dev pkg-config
          elif [ "$RUNNER_OS" = "macOS" ]; then
            sudo brew install macfuse pkg-config
          else
            echo Unsupported RUNNER_OS=$RUNNER_OS
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test ffs
        run: |
          cargo build --verbose --all
          cargo test
        
